project:
  type: website
  render:
    - "*.qmd"
    - "Hands-on_Ex/**/*.qmd"
    - "Take-home_Ex/**/*.qmd"
    - "VAST_Challenge_2026_MC1/*.qmd"
    - "VAST_Challenge_2026_MC1/*.md"
    - "!docs/**"

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on Gallery"
        href: hands-on-gallery.qmd

      - text: "Hands-on Exercise"
        menu:
          - text: "Foundations"
          - text: "Hands-on Exercise 1"
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html
          - text: "Hands-on Exercise 2"
            href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html

          - text: "Interactive and Animated Visualisation"
          - text: "Hands-on Exercise 3a"
            href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html
          - text: "Hands-on Exercise 3b"
            href: Hands-on_Ex/Hands-on_Ex03b/Hands-on_Ex03b.html
          - text: "Hands-on Exercise 4a"
            href: Hands-on_Ex/Hands-on_Ex04a/Hands-on_Ex04a.html

          - text: "Statistical Visual Analysis"
          - text: "Hands-on Exercise 4b"
            href: Hands-on_Ex/Hands-on_Ex04b/Hands-on_Ex04b.html
          - text: "Hands-on Exercise 4c"
            href: Hands-on_Ex/Hands-on_Ex04c/Hands-on_Ex04c.html
          - text: "Hands-on Exercise 4d"
            href: Hands-on_Ex/Hands-on_Ex04d/Hands-on_Ex04d.html
          - text: "Hands-on Exercise 5a"
            href: Hands-on_Ex/Hands-on_Ex05a/Hands-on_Ex05a.html
          - text: "Hands-on Exercise 5b"
            href: Hands-on_Ex/Hands-on_Ex05b/Hands-on_Ex05b.html
          - text: "Hands-on Exercise 5c"
            href: Hands-on_Ex/Hands-on_Ex05c/Hands-on_Ex05c.html
          - text: "Hands-on Exercise 5d"
            href: Hands-on_Ex/Hands-on_Ex05d/Hands-on_Ex05d.html
          - text: "Hands-on Exercise 5e"
            href: Hands-on_Ex/Hands-on_Ex05e/Hands-on_Ex05e.html

          - text: "Network, Text, and Time"
          - text: "Hands-on Exercise 7a"
            href: Hands-on_Ex/Hands-on_Ex07a/Hands-on_Ex07a.html
          - text: "Hands-on Exercise 7b"
            href: Hands-on_Ex/Hands-on_Ex07b/Hands-on_Ex07b.html
          - text: "Hands-on Exercise 8"
            href: Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html

          - text: "Geospatial Analytics"
          - text: "Hands-on Exercise 9a"
            href: Hands-on_Ex/Hands-on_Ex09a/Hands-on_Ex09a.html
          - text: "Hands-on Exercise 9b"
            href: Hands-on_Ex/Hands-on_Ex09b/Hands-on_Ex09b.html
          - text: "Hands-on Exercise 9c"
            href: Hands-on_Ex/Hands-on_Ex09c/Hands-on_Ex09c.html

          - text: "Dashboard Design"
          - text: "Hands-on Exercise 10"
            href: Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html

      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
          - text: "Technical Report"
            href: Take-home_Ex/Take-home_Ex01/Technical_Report.html
          - text: "Executive Summary"
            href: Take-home_Ex/Take-home_Ex01/Executive_Summary.html
          - text: "Take-home Exercise 2"
            href: Take-home_Ex/Take-home_Ex02/Take-home_Ex02_Technical_Report.html

    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual
